name: Build NixOS Config

on: 
  push:
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'

  workflow_dispatch:

jobs:
  build_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Flake Check
        run: nix flake check

      - name: Nix Build (Dry Run)
        run: nix build --dry-run .#nixosConfigurations.Nyx.config.system.build.toplevel

      - name: Nix Build
        run: nix build .#nixosConfigurations.Nyx.config.system.build.toplevel